[0]
stackId = 0
title="Introduction to Applied Topology"
description="Something here"
size=4
image=""
locked=false

[1]
stackId = 1
title="Neural Networks: Zero to Hero"
description="Something here"
size=2
image=""
locked=false

[2]
stackId = 2
title="Machine learning: all you need to know"
description="Something here"
size=15
image=""
locked=false

[3]
stackId = 3
title="Advanced Concepts in Algebra"
description="Something here"
size=8
image=""
locked=false

[4]
stackId = 4
title="Markov Modeling in Gene Sequencing"
description="Something here"
size=25
image=""
locked=false

[5]
stackId = 5
title="Introduction to Topology"
description="Something here"
size=12
image=""
locked=false