"""Build the DMG background from the app's own surfaces and typeface.

Run from the repository root:

    python3 scripts/make-dmg-background.py

Needs `fonttools`, `brotli` (to read the woff2 faces) and `rsvg-convert` on
PATH. Writes src-tauri/dmg/background.png, plus an @2x copy and a preview with
the icons composited, which are not shipped.

Two things drive every number here.

First, geometry is Finder's, not ours. Icon size is fixed at 128pt — the
bundler's `bundle_dmg.sh` defaults to it and Tauri exposes no way to pass
`--icon-size` — so the icons occupy known boxes and the artwork has to stay out
of them. The icon centres below are mirrored in tauri.conf.json under
bundle.macOS.dmg; change them in both places or the layout drifts.

Second, text is emitted as outlines rather than font references. rsvg-convert
resolves families through fontconfig, which does not see the project's bundled
woff2 files, so naming Public Sans there silently renders Helvetica instead.
Outlines make the SVG self-contained and the output independent of what happens
to be installed.

Kept flat on purpose, for the reason make-icons.py gives for the icon: the app's
surfaces are flat with hard offset shadows, so a gradient here would disagree
with both the icon and the app behind it.
"""

import subprocess
import sys
from pathlib import Path

from fontTools.misc.transform import Transform
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parent.parent
FONT_DIR = ROOT / "static" / "fonts"
OUT_DIR = ROOT / "src-tauri" / "dmg"

# ── Window and icon geometry, in points. Mirrored in tauri.conf.json. ────────
W, H = 660, 400
ICON = 128                      # Finder's icon size; not configurable
APP_CENTRE = (180, 158)
APPS_CENTRE = (480, 158)
LABEL_BASELINE = 240            # roughly where Finder draws the item name

# ── Palette, from src/app.css ───────────────────────────────────────────────
DESK = "#efeee9"                # --desk
ACCENT = "#1d628c"              # --accent
INK_2 = "#4b4a47"
INK_3 = "#797873"
MUTED = "#8a8983"

WEIGHTS = {400: "public-sans-latin-400-normal.woff2",
           600: "public-sans-latin-600-normal.woff2",
           700: "public-sans-latin-700-normal.woff2"}

_fonts: dict[int, tuple] = {}


def font(weight: int):
    if weight not in _fonts:
        f = TTFont(FONT_DIR / WEIGHTS[weight])
        _fonts[weight] = (f.getGlyphSet(), f.getBestCmap(),
                          f["head"].unitsPerEm, f["hmtx"])
    return _fonts[weight]


def text_path(weight: int, text: str, size: float, tracking: float = 0.0):
    """Return (svg path data, advance width) for `text`, origin at (0, 0)."""
    glyphs, cmap, upm, hmtx = font(weight)
    scale = size / upm
    pen = SVGPathPen(glyphs)
    x = 0.0
    for ch in text:
        name = cmap.get(ord(ch))
        if name is None:
            x += size * 0.5 + tracking
            continue
        # Font Y points up, SVG Y points down.
        glyphs[name].draw(TransformPen(pen, Transform(scale, 0, 0, -scale, x, 0)))
        x += hmtx[name][0] * scale + tracking
    return pen.getCommands(), (x - tracking if text else 0.0)


def centred(weight: int, text: str, size: float, cx: float, baseline: float,
            fill: str, tracking: float = 0.0) -> str:
    d, width = text_path(weight, text, size, tracking)
    return (f'<path d="{d}" fill="{fill}" '
            f'transform="translate({cx - width / 2:.2f} {baseline})"/>')


def build_svg() -> str:
    """
    Deliberately sparse. An earlier draft drew a dashed accent 'drop slot'
    around the Applications icon, echoing the app's own drag-onto-a-pile
    pattern. It came out wrong twice over: Finder's label lands on the slot's
    bottom edge, and the slot competed with the folder icon, which is already
    the most saturated thing in the window. The arrow carries the instruction
    on its own.
    """
    y = APP_CENTRE[1]
    gap_centre = (APP_CENTRE[0] + APPS_CENTRE[0]) / 2
    return "\n".join([
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{W}" height="{H}" '
        f'viewBox="0 0 {W} {H}">',
        "<!-- Generated by scripts/make-dmg-background.py. Edit that, not this. -->",
        f'<rect width="{W}" height="{H}" fill="{DESK}"/>',

        # The one accent moment, living in the gap between the icon boxes so it
        # can never sit under an icon.
        f'<g stroke="{ACCENT}" fill="none" stroke-width="2" '
        f'stroke-linecap="round" stroke-linejoin="round">',
        f'<line x1="278" y1="{y}" x2="382" y2="{y}"/>',
        f'<polyline points="372,{y - 8} 382,{y} 372,{y + 8}"/>',
        "</g>",
        centred(600, "DRAG TO INSTALL", 9.5, gap_centre, y + 30, INK_3, 1.35),

        # Signature, below Finder's labels and close enough to them to read as
        # one block rather than drifting to the window's floor.
        centred(700, "PaperStack", 15, gap_centre, 310, INK_2, -0.15),
        centred(400, "A desktop research workspace", 10.5, gap_centre, 329, MUTED),
        "</svg>",
    ])


def rasterise(svg: Path, out: Path, scale: int) -> None:
    subprocess.run(["rsvg-convert", "-w", str(W * scale), "-h", str(H * scale),
                    str(svg), "-o", str(out)], check=True)
    print(f"  {out.relative_to(ROOT)}  {W * scale}x{H * scale}")


def build_preview(background: Path, out: Path) -> None:
    """Composite the real icons at Finder's geometry, to check the artwork clears them."""
    try:
        from PIL import Image
    except ImportError:
        print("  (skipping preview: Pillow not installed)")
        return

    apps_icns = Path("/System/Library/CoreServices/CoreTypes.bundle"
                     "/Contents/Resources/ApplicationsFolderIcon.icns")
    if not apps_icns.exists():
        print("  (skipping preview: no Applications folder icon on this system)")
        return

    scale = 2
    tmp = out.parent / "_apps.png"
    subprocess.run(["sips", "-s", "format", "png", "--out", str(tmp), str(apps_icns)],
                   check=True, capture_output=True)

    canvas = Image.open(background).convert("RGBA")
    for icon_path, centre in (
        (ROOT / "src-tauri/icons/variants/paperstack-bold-256.png", APP_CENTRE),
        (tmp, APPS_CENTRE),
    ):
        icon = Image.open(icon_path).convert("RGBA").resize(
            (ICON * scale, ICON * scale), Image.LANCZOS)
        canvas.alpha_composite(icon, (int(centre[0] * scale - ICON * scale / 2),
                                      int(centre[1] * scale - ICON * scale / 2)))

    labels = [f'<svg xmlns="http://www.w3.org/2000/svg" width="{W}" height="{H}">']
    for text, centre in (("PaperStack", APP_CENTRE), ("Applications", APPS_CENTRE)):
        labels.append(centred(400, text, 11, centre[0], LABEL_BASELINE, "#20201e"))
    labels.append("</svg>")

    label_svg = out.parent / "_labels.svg"
    label_png = out.parent / "_labels.png"
    label_svg.write_text("\n".join(labels))
    rasterise(label_svg, label_png, scale)
    canvas.alpha_composite(Image.open(label_png).convert("RGBA"), (0, 0))
    canvas.convert("RGB").save(out)

    for scratch in (tmp, label_svg, label_png):
        scratch.unlink(missing_ok=True)
    print(f"  {out.relative_to(ROOT)}  (with icons, as Finder shows it)")


def main() -> int:
    if not FONT_DIR.exists():
        print(f"missing {FONT_DIR}", file=sys.stderr)
        return 1
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    svg = OUT_DIR / "background.svg"
    svg.write_text(build_svg())
    print("wrote:")

    # Finder maps one image pixel to one point and does not scale, so a bare 2x
    # PNG in a 660x400 window would show only its top-left quarter. The way to
    # get a sharp background on a Retina display is a TIFF carrying both
    # representations — 660x400 at 72dpi and 1320x800 at 144dpi — which is what
    # `tiffutil -cathidpicheck` builds and what tauri.conf.json points at. The
    # two PNGs are inputs to that, and are also handy to look at on their own.
    one = OUT_DIR / "background.png"
    two = OUT_DIR / "background@2x.png"
    rasterise(svg, one, 1)
    rasterise(svg, two, 2)

    tiff = OUT_DIR / "background.tiff"
    subprocess.run(["tiffutil", "-cathidpicheck", str(one), str(two), "-out", str(tiff)],
                   check=True, capture_output=True)
    print(f"  {tiff.relative_to(ROOT)}  660x400 @72dpi + 1320x800 @144dpi  <- shipped")

    build_preview(two, OUT_DIR / "preview.png")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
